// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC94pP6Zfid7mGjoXxQZp4QiiGk3c-sK9o',
    appId: '1:792466043013:web:49ceeec382703d065339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    authDomain: 'fir-apptest-c3e4e.firebaseapp.com',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
    measurementId: 'G-P16VRNW8KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_bPzS8OFzkC_VxVEej9EJVNEXCFdTOY',
    appId: '1:792466043013:android:e7d960990c24122d5339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTtuj88qDGa_CxvVnhwDJJdBID9lSWpw',
    appId: '1:792466043013:ios:b948b30b836a1d675339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
    androidClientId: '792466043013-0fgnsalsb4po7n490n9ovq46abqb9080.apps.googleusercontent.com',
    iosClientId: '792466043013-3e8r0p2b1h88dd4nnumbavogkv8r62n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC94pP6Zfid7mGjoXxQZp4QiiGk3c-sK9o',
    appId: '1:792466043013:web:8e392762fd8b9fcd5339ec',
    messagingSenderId: '792466043013',
    projectId: 'fir-apptest-c3e4e',
    authDomain: 'fir-apptest-c3e4e.firebaseapp.com',
    databaseURL: 'https://fir-apptest-c3e4e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-apptest-c3e4e.appspot.com',
    measurementId: 'G-CMSN095ERJ',
  );
}
